#! /usr/bin/env Rscript
# This script is a forked version of https://github.com/yihui/knitr-jekyll/blob/gh-pages/build.R

"
Usage: knit.r INPUT OUTPUT 
" -> doc

opts <- docopt::docopt(doc)
ifile <- opts[["INPUT"]]
ofile <- opts[["OUTPUT"]]

#----------------------------


# fall back on '/' if baseurl is not specified
baseurl = yaml::yaml.load_file("./_config.yml")$baseurl
knitr::opts_knit$set(base.url = paste0(baseurl, '/'))

knitr::render_jekyll()

# input/output filenames are passed as two additional arguments to Rscript
d = gsub('^_|[.][a-zA-Z]+$', '', ifile)
knitr::opts_chunk$set(
  fig.path   = sprintf('figure/%s/', d),
  cache.path = sprintf('cache/%s/', d)
)
knitr::opts_knit$set(width = 70)
knitr::knit(ifile, ofile, quiet = TRUE, encoding = 'UTF-8', envir = new.env())

figures <- list.files(knitr::opts_chunk$get("fig.path"), full.names = TRUE)

# We don't need examples without figures; delete it.
if(length(figures) == 0){
  file.remove(ifile, ofile)
  warning(sprintf("No figures are generated by %s", ifile))
  quit()
}

images <- paste0(sprintf(" - %s/%s", baseurl, figures), collapse = "\n")

txt <- sub("FRONTFOMATTER_IMAGES", 
           images, 
           paste(readLines(ofile), collapse = "\n"))

cat(txt, file = ofile)
