#! /usr/local/bin/r

# This script is a forked version of https://github.com/yihui/knitr-jekyll/blob/gh-pages/build.R

local({
  # fall back on '/' if baseurl is not specified
  baseurl = servr:::jekyll_config('.', 'baseurl', '/')
  knitr::opts_knit$set(base.url = paste0(baseurl, '/'))

  knitr::render_jekyll()
  
  # input/output filenames are passed as two additional arguments to Rscript
  d = gsub('^_|[.][a-zA-Z]+$', '', argv[1])
  knitr::opts_chunk$set(
    fig.path   = sprintf('figure/%s/', d),
    cache.path = sprintf('cache/%s/', d)
  )
  knitr::opts_knit$set(width = 70)
  knitr::knit(argv[1], argv[2], quiet = TRUE, encoding = 'UTF-8', envir = .GlobalEnv)
 
  figures <- list.files(knitr::opts_chunk$get("fig.path"), full.names = TRUE)

  # We don't need examples without figures; delete it.
  if(length(figures) == 0){
    file.remove(argv[1], argv[2])
    warning(sprintf("No figures are generated by %s", argv[1]))
    return()
  }

  images <- paste0(sprintf(" - %s/%s", baseurl, figures), collapse = "\n")
  
  txt <- sub("FRONTFOMATTER_IMAGES", 
             images, 
             paste(readLines(argv[2]), collapse = "\n"))

  cat(txt, file = argv[2])
})
