---
title: |
  Summary of principal component analysis as HTML table
rdname: sjt.pca
date: 2015-10-22
output: html_document
layout: article
category: sjplot
images:
FRONTFOMATTER_IMAGES
---

```{r, echo = FALSE, message = FALSE}
library(ggplot2)
library(sjPlot)
```

```{r sjt.pca, cache = TRUE}
## Not run: 
##D # randomly create data frame with 7 items, each consisting of 4 categories
##D likert_4 <- data.frame(sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.2, 0.3, 0.1, 0.4)),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.5, 0.25, 0.15, 0.1)),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.4, 0.15, 0.25, 0.2)),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.25, 0.1, 0.4, 0.25)),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.1, 0.4, 0.4, 0.1)),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE),
##D                        sample(1:4,
##D                               500,
##D                               replace = TRUE,
##D                               prob = c(0.35, 0.25, 0.15, 0.25)))
##D 
##D # Create variable labels
##D colnames(likert_4) <- c("V1", "V2", "V3", "V4", "V5", "V6", "V7")
##D 
##D # show table
##D sjt.pca(likert_4)
##D 
##D # -------------------------------
##D # Data from the EUROFAMCARE sample dataset
##D # -------------------------------
##D library(sjmisc)
##D data(efc)
##D 
##D # retrieve variable and value labels
##D varlabs <- get_label(efc)
##D 
##D # recveive first item of COPE-index scale
##D start <- which(colnames(efc) == "c82cop1")
##D # recveive last item of COPE-index scale
##D end <- which(colnames(efc) == "c90cop9")
##D 
##D # create data frame with COPE-index scale
##D mydf <- as.data.frame(efc[, c(start:end)])
##D colnames(mydf) <- varlabs[c(start:end)]
##D 
##D sjt.pca(mydf)
##D 
##D # -------------------------------
##D # auto-detection of labels
##D # -------------------------------
##D sjt.pca(efc[, c(start:end)])
## End(Not run)



```