---
title: |
  Variable Importance (VIMP) data object
rdname: gg_vimp.rfsrc
date: 1991-05-31
output: html_document
layout: article
category: ggrandomforests
images:
FRONTFOMATTER_IMAGES
---

```{r, echo = FALSE, message = FALSE}
library(ggplot2)
library(ggRandomForests)
```

```{r gg_vimp.rfsrc, cache = TRUE}
## ------------------------------------------------------------
## classification example
## ------------------------------------------------------------
## -------- iris data
# rfsrc_iris <- rfsrc(Species ~ ., data = iris)
data(rfsrc_iris, package="ggRandomForests")
gg_dta <- gg_vimp(rfsrc_iris)
plot(gg_dta)

## ------------------------------------------------------------
## regression example
## ------------------------------------------------------------
## Not run: 
##D ## -------- air quality data
##D # rfsrc_airq <- rfsrc(Ozone ~ ., airquality)
##D data(rfsrc_airq, package="ggRandomForests")
##D gg_dta <- gg_vimp(rfsrc_airq)
##D plot(gg_dta)
## End(Not run)

## -------- Boston data
data(rfsrc_Boston, package="ggRandomForests")
gg_dta <- gg_vimp(rfsrc_Boston)
plot(gg_dta)

## Not run: 
##D ## -------- mtcars data
##D data(rfsrc_mtcars, package="ggRandomForests")
##D gg_dta <- gg_vimp(rfsrc_mtcars)
##D plot(gg_dta)
## End(Not run)
## ------------------------------------------------------------
## survival example
## ------------------------------------------------------------
## Not run: 
##D ## -------- veteran data
##D data(rfsrc_veteran, package="ggRandomForests")
##D gg_dta <- gg_vimp(rfsrc_veteran)
##D plot(gg_dta)
## End(Not run)

## -------- pbc data
data(rfsrc_pbc, package="ggRandomForests")
gg_dta <- gg_vimp(rfsrc_pbc)
plot(gg_dta)

# Restrict to only the top 10.
gg_dta <- gg_vimp(rfsrc_pbc, n_var=10)
plot(gg_dta)



```