---
title: |
  Summary of stacked frequencies as HTML table
rdname: sjt.stackfrq
date: 2015-10-22
output: html_document
layout: article
category: sjplot
images:
FRONTFOMATTER_IMAGES
---

```{r, echo = FALSE, message = FALSE}
library(ggplot2)
library(sjPlot)
```

```{r sjt.stackfrq, cache = TRUE}
# -------------------------------
# random sample
# -------------------------------
# prepare data for 4-category likert scale, 5 items
likert_4 <- data.frame(as.factor(sample(1:4,
                                        500,
                                        replace = TRUE,
                                        prob = c(0.2, 0.3, 0.1, 0.4))),
                       as.factor(sample(1:4,
                                        500,
                                        replace = TRUE,
                                        prob = c(0.5, 0.25, 0.15, 0.1))),
                       as.factor(sample(1:4,
                                        500,
                                        replace = TRUE,
                                        prob = c(0.25, 0.1, 0.4, 0.25))),
                       as.factor(sample(1:4,
                                        500,
                                        replace = TRUE,
                                        prob = c(0.1, 0.4, 0.4, 0.1))),
                       as.factor(sample(1:4,
                                        500,
                                        replace = TRUE,
                                        prob = c(0.35, 0.25, 0.15, 0.25))))
# create labels
levels_4 <- c("Independent",
              "Slightly dependent",
              "Dependent",
              "Severely dependent")

# create item labels
items <- c("Q1", "Q2", "Q3", "Q4", "Q5")

# plot stacked frequencies of 5 (ordered) item-scales
## Not run: 
##D sjt.stackfrq(likert_4, valuelabels = levels_4, varlabels = items)
##D 
##D 
##D # -------------------------------
##D # Data from the EUROFAMCARE sample dataset
##D # Auto-detection of labels
##D # -------------------------------
##D library(sjmisc)
##D data(efc)
##D # recveive first item of COPE-index scale
##D start <- which(colnames(efc) == "c82cop1")
##D # recveive first item of COPE-index scale
##D end <- which(colnames(efc) == "c90cop9")
##D 
##D sjt.stackfrq(efc[, c(start:end)],
##D              alternateRowColors = TRUE)
##D 
##D sjt.stackfrq(efc[, c(start:end)],
##D              alternateRowColors = TRUE,
##D              showN = TRUE,
##D              showNA = TRUE)
##D 
##D 
##D # --------------------------------
##D # User defined style sheet
##D # --------------------------------
##D sjt.stackfrq(efc[, c(start:end)],
##D              alternateRowColors = TRUE,
##D              showTotalN = TRUE,
##D              showSkew = TRUE,
##D              showKurtosis = TRUE,
##D              CSS = list(css.ncol = "border-left:1px dotted black;",
##D                         css.summary = "font-style:italic;"))
## End(Not run)



```