---
title: |
  Autoplot time series models (like AR, ARIMA)
rdname: autoplot.tsmodel
date: 2015-05-12
output: html_document
layout: article
category: ggfortify
images:
FRONTFOMATTER_IMAGES
---

```{r, echo = FALSE, message = FALSE}
library(ggplot2)
library(ggfortify)
```

```{r autoplot.tsmodel, cache = TRUE}

d.ar <- stats::ar(AirPassengers)
autoplot(d.ar)
autoplot(d.ar, predict = predict(d.ar, n.ahead = 5))
autoplot(stats::arima(UKgas), data = UKgas)
autoplot(forecast::arfima(AirPassengers))
autoplot(forecast::nnetar(UKgas), is.date = FALSE)

d.holt <- stats::HoltWinters(USAccDeaths)
autoplot(d.holt)
autoplot(d.holt, predict = predict(d.holt, n.ahead = 5))
autoplot(d.holt, predict = predict(d.holt, n.ahead = 5, prediction.interval = TRUE))

form <- function(theta){
  dlm::dlmModPoly(order=1, dV=exp(theta[1]), dW=exp(theta[2]))
}
model <- form(dlm::dlmMLE(Nile, parm=c(1, 1), form)$par)
filtered <- dlm::dlmFilter(Nile, model)
autoplot(filtered)
autoplot(dlm::dlmSmooth(filtered))



```